In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\USER\\anaconda3\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [2]:
string = tf.Variable("Hello, TensorFlow!", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [11]:
rank1_tensor = tf.Variable([1, 2, 3], dtype=tf.int16)
rank2_tensor = tf.Variable([
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
], dtype=tf.int16)
rank3_tensor = tf.Variable([
    [
        [13, 14, 15],
        [16, 17, 18]
    ],
    [
        [19, 20, 21],
        [22, 23, 24]
    ],
    [
        [25, 26, 27],
        [28, 29, 30]
    ]
], dtype=tf.int16)
rank4_tensor = tf.Variable([
    [[
        [13, 14, 15],
        [16, 17, 18]
    ]
    ],
    [[
        [19, 20, 21],
        [22, 23, 24]
    ]
    ],
    [[
        [25, 26, 27],
        [28, 29, 30]
    ]
    ],
    [[
        [31, 32, 33],
        [34, 35, 36]
    ]
    ]
], dtype=tf.int16)

In [12]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
tf.rank(rank2_tensor).numpy()

2

In [14]:
rank2_tensor.shape

TensorShape([3, 3])

In [15]:
tf.rank(rank3_tensor).numpy()

3

In [16]:
print(rank3_tensor.numpy())

[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]]]


In [17]:
tensor1 = tf.reshape(rank1_tensor, [3,1])
print(tensor1)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int16)


In [18]:

tf.rank(rank4_tensor).numpy()   

4

In [19]:
print(rank4_tensor.numpy())

[[[[13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]]]


 [[[25 26 27]
   [28 29 30]]]


 [[[31 32 33]
   [34 35 36]]]]


In [25]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print(matrix)
print()
print(matrix.shape)
print()
print(matrix.dtype)
print()
print(tf.rank(matrix).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

(2, 3)

<dtype: 'int32'>

2
