In [2]:
import tensorflow as tf

In [3]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = tf.add(a, b)
# c = a + b
print(c)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [4]:
c = a - b
print(c)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [5]:
c = tf.divide(a, b)
print(c)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [6]:
c = tf.multiply(a, b)
print(c)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [7]:
mat1 = tf.constant([[1, 2], [3, 4]])
mat2 = tf.constant([[5, 6], [7, 8]])    
product = tf.matmul(mat1, mat2)
print(product)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [8]:
print(tf.transpose(mat1))

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [9]:
print(tf.transpose(product))

tf.Tensor(
[[19 43]
 [22 50]], shape=(2, 2), dtype=int32)


In [11]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tensor)
print("Original Shape: ", tensor.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Original Shape:  (2, 3)


In [12]:
reshaped = tf.reshape(tensor, (3, 2))
print(reshaped)
print("Reshaped Shape: ", reshaped.shape)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Reshaped Shape:  (3, 2)


In [16]:
temp = tf.constant([[[1, 2], [3, 4]], 
                    [[5, 6], [7, 8]], 
                    [[9, 10], [11, 12]]
                    ])

In [21]:
sliced = tensor[0:2:2]
print(sliced)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [22]:
print(temp)

tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)
